# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Build the app without using existing code signing settings"
  lane :build_banaan do
    xcversion(version: "9.2")
    gym(
      project: "banaan.xcodeproj",
      configuration: "Release",
      scheme: "banaan",
      # output_directory: "path/to/dir",   # Destination directory. Defaults to current directory.
      output_name: "banaan-ios.ipa",       # specify the name of the .ipa file to generate (including file extension)
      sdk: "iOS 11.2",                     # use SDK as the name or path of the base SDK when building the project.
    )
  end

  desc "Download signing filed, build the app and run the tests"
  lane :build_and_test do
    build_signed
    execute_tests
  end

  desc "Download signign files and build the app"
  lane :build_signed do
    match(app_identifier: "io.nevercode.banaan", type: "appstore", readonly: true)
    gym(
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "io.nevercode.banaan" => "match AppStore io.nevercode.banaan"
        }
      }
    )
  end

  desc "Build without signing for simulator"
  lane :simulator_build do
    xcbuild(
      project: "banaan.xcodeproj",
      configuration: "Release",
      scheme: "banaan",
      xcargs: "-sdk iphonesimulator",
    )
  end

  desc "Run application's test suite"
  lane :execute_tests do
    run_tests(
      project: "banaan.xcodeproj",
      devices: ["iPhone 6s", "iPad Air"],
      scheme: "banaan",
      fail_build: false,
    )
    trainer(output_directory: ENV["NC_XUNIT_RESULTS_DIR"])
  end
end
