# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

desc "Build the app"
lane :build_banaan do
  xcversion(version: "9.2")
  gym(
    project: "banaan.xcodeproj",
    configuration: "Release",
    scheme: "banaan",
    # output_directory: "path/to/dir",   # Destination directory. Defaults to current directory.
    output_name: "banaan-ios.ipa",       # specify the name of the .ipa file to generate (including file extension)
    sdk: "iOS 11.2",                     # use SDK as the name or path of the base SDK when building the project.
  )
end

lane :build_and_setup_signing do
  match(app_identifier: "io.nevercode.banaan", type: "appstore", readonly: true)
  gym(
    export_method: "app-store",
    export_options: {
      provisioningProfiles: {
        "io.nevercode.banaan" => "match AppStore io.nevercode.banaan"
      }
    }
  )
end

platform :android do
  desc "Description of what the lane does"
  lane :custom_lane do
    sh "echo 'tere talv'"
  end
end

platform :ios do
  lane :test_banaan do
    run_tests(workspace: "banaan.xcworkspace",
              devices: ["iPhone 6s"],  # , "iPad Air"],
              scheme: "banaan")
  end
end
